### PR TITLE
Installation

### PR DESCRIPTION
**Pull request by rezahakimazar**
This adds a chapter on how to install Quarto

### CODE REVIEW

**Comment by lnnrtwttkhn** [comment]
- [ ] Add image captions
- [ ] Add tabsets for Windows download instructions (see [e5b5333](https://github.com/lnnrtwttkhn/quarto-book/pull/30/commits/e5b533370af9fb5c868a28243e5b633e5007e3f8))
- [ ] Add installation instructions for macOS and Linux

**Comment by rezahakimazar** [comment]
Added image captions and tabsets.

**Comment by lnnrtwttkhn** [comment]
Ready to merge 🚀 Thank you for this PR @rezahakimazar!

**Comment by lnnrtwttkhn** [comment]
@all-contributors please add @rezahakimazar for code, content

**Comment by lnnrtwttkhn** [comment]
@all-contributors please add @rezahakimazar for code, content

**Pull request merged**
